#! /bin/sh
# kcminputrc Mouse cursorTheme 'Oxygen_Black'
kcminputrc_mouse_cursortheme="default"
# kcminputrc Mouse cursorSize ''
kcminputrc_mouse_cursorsize=""
# ksplashrc KSplash Theme RHEL6
ksplashrc_ksplash_theme="RHEL6"
# ksplashrc KSplash Engine KSplashX
ksplashrc_ksplash_engine="KSplashX"
# kcmrandrrc Display ApplyOnStartup false
kcmrandrrc_display_applyonstartup="false"
# kcmrandrrc [Screen0]
# kcmrandrrc [Screen1]
# kcmrandrrc [Screen2]
# kcmrandrrc [Screen3]
# kcmfonts General forceFontDPI 0
kcmfonts_general_forcefontdpi="0"
# kdeglobals Locale Language '' # trigger requesting languages from KLocale
kdeglobals_locale_language=""
klocale_languages=en_US
