# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1501172399);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1505393521);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1501171071);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1501171302);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1501171182);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1501170866);
user_pref("browser.laterrun.bookkeeping.sessionCount", 19);
user_pref("browser.migration.version", 42);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1501171166094");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1501172879094");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1501170939585");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1501174539585");
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.region", "US");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20170614092444");
user_pref("browser.slowStartup.averageTime", 13765);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20170810000335");
user_pref("browser.startup.homepage_override.mstone", "52.3.0");
user_pref("browser.tabs.remote.autostart.2", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\",\"sync-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"pocket-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\",\"PanelUI-contents\",\"addon-bar\"],\"currentVersion\":6,\"newElementCount\":0}");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1501170946830");
user_pref("datareporting.sessions.current.activeTicks", 2);
user_pref("datareporting.sessions.current.firstPaint", 39292);
user_pref("datareporting.sessions.current.main", 1371);
user_pref("datareporting.sessions.current.sessionRestored", 47218);
user_pref("datareporting.sessions.current.startTime", "1505393471993");
user_pref("datareporting.sessions.current.totalTime", 77);
user_pref("datareporting.sessions.currentIndex", 18);
user_pref("datareporting.sessions.previous.0", "{\"s\":1501170859531,\"a\":0,\"t\":4,\"c\":false,\"m\":1790,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1501170933516,\"a\":3,\"t\":14,\"c\":true,\"m\":221,\"fp\":3338,\"sr\":3211}");
user_pref("datareporting.sessions.previous.10", "{\"s\":1501172024637,\"a\":4,\"t\":18,\"c\":true,\"m\":140,\"fp\":1987,\"sr\":2158}");
user_pref("datareporting.sessions.previous.11", "{\"s\":1501172043266,\"a\":1,\"t\":4,\"c\":true,\"m\":181,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.12", "{\"s\":1501172048382,\"a\":1,\"t\":4,\"c\":true,\"m\":111,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.13", "{\"s\":1501172053475,\"a\":1,\"t\":4,\"c\":true,\"m\":110,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.14", "{\"s\":1501172058099,\"a\":1,\"t\":3,\"c\":true,\"m\":121,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.15", "{\"s\":1501172061715,\"a\":1,\"t\":4,\"c\":true,\"m\":121,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.16", "{\"s\":1501172066523,\"a\":1,\"t\":3,\"c\":true,\"m\":110,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.17", "{\"s\":1501172366062,\"a\":3,\"t\":28,\"c\":false,\"m\":1690,\"fp\":4065,\"sr\":4568}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1501171040076,\"a\":4,\"t\":44,\"c\":true,\"m\":360,\"fp\":2229,\"sr\":2317}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1501171085162,\"a\":2,\"t\":10,\"c\":true,\"m\":721,\"fp\":2684,\"sr\":2776}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1501171151462,\"a\":2,\"t\":161,\"c\":true,\"m\":210,\"fp\":2375,\"sr\":2536}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1501171313298,\"a\":2,\"t\":11,\"c\":true,\"m\":240,\"fp\":2186,\"sr\":2279}");
user_pref("datareporting.sessions.previous.6", "{\"s\":1501171325412,\"a\":1,\"t\":5,\"c\":true,\"m\":841,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.7", "{\"s\":1501171331173,\"a\":1,\"t\":14,\"c\":true,\"m\":120,\"fp\":2487,\"sr\":2596}");
user_pref("datareporting.sessions.previous.8", "{\"s\":1501171970958,\"a\":2,\"t\":14,\"c\":true,\"m\":1011,\"fp\":4021,\"sr\":4618}");
user_pref("datareporting.sessions.previous.9", "{\"s\":1501171986135,\"a\":1,\"t\":5,\"c\":true,\"m\":130,\"fp\":1915,\"sr\":2228}");
user_pref("e10s.rollout.cohort", "test");
user_pref("e10s.rollout.cohortSample", "0.922044");
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{\"firefox@getpocket.com\":{\"version\":\"1.0.5\",\"type\":\"extension\",\"descriptor\":\"/usr/lib64/firefox/browser/features/firefox@getpocket.com.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":true,\"dependencies\":[],\"hasEmbeddedWebExtension\":false},\"webcompat@mozilla.org\":{\"version\":\"1.0\",\"type\":\"extension\",\"descriptor\":\"/usr/lib64/firefox/browser/features/webcompat@mozilla.org.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":true,\"dependencies\":[],\"hasEmbeddedWebExtension\":false},\"e10srollout@mozilla.org\":{\"version\":\"1.10\",\"type\":\"extension\",\"descriptor\":\"/usr/lib64/firefox/browser/features/e10srollout@mozilla.org.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":true,\"dependencies\":[],\"hasEmbeddedWebExtension\":false},\"aushelper@mozilla.org\":{\"version\":\"2.0\",\"type\":\"extension\",\"descriptor\":\"/usr/lib64/firefox/browser/features/aushelper@mozilla.org.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":true,\"dependencies\":[],\"hasEmbeddedWebExtension\":false}}");
user_pref("extensions.databaseSchema", 19);
user_pref("extensions.e10s.rollout.blocklist", "{dc572301-7619-498c-a57d-39143191b318};support@lastpass.com;");
user_pref("extensions.e10s.rollout.hasAddon", false);
user_pref("extensions.e10s.rollout.policy", "51set1");
user_pref("extensions.e10sBlockedByAddons", false);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:52.3.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1501172399);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "52.3.0");
user_pref("extensions.lastPlatformVersion", "52.3.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-system-defaults\":{\"webcompat@mozilla.org\":{\"d\":\"/usr/lib64/firefox/browser/features/webcompat@mozilla.org.xpi\",\"e\":true,\"v\":\"1.0\",\"st\":1502344523000},\"aushelper@mozilla.org\":{\"d\":\"/usr/lib64/firefox/browser/features/aushelper@mozilla.org.xpi\",\"e\":true,\"v\":\"2.0\",\"st\":1502344523000},\"e10srollout@mozilla.org\":{\"d\":\"/usr/lib64/firefox/browser/features/e10srollout@mozilla.org.xpi\",\"e\":true,\"v\":\"1.10\",\"st\":1502344523000},\"firefox@getpocket.com\":{\"d\":\"/usr/lib64/firefox/browser/features/firefox@getpocket.com.xpi\",\"e\":true,\"v\":\"1.0.5\",\"st\":1502344523000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"52.3.0\",\"st\":1502344523000}}}");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1501171216);
user_pref("media.gmp-gmpopenh264.version", "1.6");
user_pref("media.gmp-manager.buildID", "20170614092444");
user_pref("media.gmp-manager.lastCheck", 1501171214);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 122334);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("services.blocklist.addons.checked", 1505392972);
user_pref("services.blocklist.clock_skew_seconds", 548);
user_pref("services.blocklist.last_update_seconds", 1505392972);
user_pref("services.blocklist.plugins.checked", 1505392972);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1505393473);
user_pref("toolkit.telemetry.cachedClientID", "4cf30000-f5c0-4de3-9a0c-6f472cf1e637");
user_pref("toolkit.telemetry.previousBuildID", "20170810000335");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
